# Generated by Django 6.0.7 on 2026-07-23 11:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Upload an icon or SVG', null=True, upload_to='services/')),
                ('short_description', models.TextField(help_text='For the homepage cards')),
                ('detailed_description', tinymce.models.HTMLField(blank=True, help_text='For the services detail page')),
            ],
        ),
    ]
