# Generated by Django 6.0.7 on 2026-07-23 11:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Trade California International', max_length=255)),
                ('tagline', models.CharField(default='Connecting American Products with International Markets', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_headline', models.CharField(default='Expand Your Global Reach', max_length=255)),
                ('hero_subtext', models.TextField(default='Premium Trade & International Business Platform')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_cta_text', models.CharField(default='Register Now', max_length=50)),
                ('hero_cta_link', models.CharField(default='/registration/', max_length=255)),
                ('about_text', tinymce.models.HTMLField(blank=True, default='<p>Trade California International is your trusted partner...</p>')),
                ('contact_email', models.EmailField(blank=True, default='contact@tradecalifornia.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='+1 (800) 123-4567', max_length=50)),
                ('chatbot_embed_code', models.TextField(blank=True, help_text='Paste your Tawk.to or other chatbot script here')),
                ('analytics_script', models.TextField(blank=True, help_text='Google Analytics or similar')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
