# Generated by Django 6.0.7 on 2026-07-25 05:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyvalue_mentor_sitesettings_mission_statement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='About Us', max_length=255)),
                ('hero_subtext', models.TextField(default='Trade California International')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('hero_opacity_percentage', models.PositiveIntegerField(default=20, help_text='Opacity of the hero background image (0-100)')),
                ('mission_statement', models.TextField(blank=True, default='To connect American businesses with global opportunities.')),
                ('vision_statement', models.TextField(blank=True, default='Empowering trade without borders.')),
                ('about_text', tinymce.models.HTMLField(blank=True, default='<p>Trade California International is your trusted partner...</p>')),
                ('cta_headline', models.CharField(default='Ready to Partner With Us?', max_length=255)),
                ('cta_subtext', models.TextField(blank=True, default='Join thousands of verified businesses expanding their global footprint through Trade California International.')),
                ('cta_button_text', models.CharField(default='Apply to Partner Program', max_length=50)),
                ('cta_button_link', models.CharField(default='/registration/', max_length=255)),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Contact Us', max_length=255)),
                ('hero_subtext', models.TextField(default='Get in touch with our expert team today.')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('hero_opacity_percentage', models.PositiveIntegerField(default=20, help_text='Opacity of the hero background image (0-100)')),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Expand Your Global Reach', max_length=255)),
                ('hero_subtext', models.TextField(default='Premium Trade & International Business Platform')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('hero_opacity_percentage', models.PositiveIntegerField(default=30, help_text='Opacity of the hero background image (0-100)')),
                ('hero_cta_text', models.CharField(blank=True, default='Register Now', max_length=50)),
                ('hero_cta_link', models.CharField(blank=True, default='/registration/', max_length=255)),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Our Products', max_length=255)),
                ('hero_subtext', models.TextField(default='Explore our premium catalog of American products.')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('hero_opacity_percentage', models.PositiveIntegerField(default=20, help_text='Opacity of the hero background image (0-100)')),
            ],
            options={
                'verbose_name': 'Products Page Settings',
                'verbose_name_plural': 'Products Page Settings',
            },
        ),
        migrations.CreateModel(
            name='RegistrationPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Partner Registration', max_length=255)),
                ('hero_subtext', models.TextField(default='Join our global network of verified trade partners.')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('hero_opacity_percentage', models.PositiveIntegerField(default=20, help_text='Opacity of the hero background image (0-100)')),
            ],
            options={
                'verbose_name': 'Registration Page Settings',
                'verbose_name_plural': 'Registration Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ServicesPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Our Services', max_length=255)),
                ('hero_subtext', models.TextField(default='Comprehensive solutions for international trade.')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('hero_opacity_percentage', models.PositiveIntegerField(default=20, help_text='Opacity of the hero background image (0-100)')),
            ],
            options={
                'verbose_name': 'Services Page Settings',
                'verbose_name_plural': 'Services Page Settings',
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_background',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_headline',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_subtext',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mission_statement',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='vision_statement',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://twitter.com'),
        ),
    ]
