# Generated by Django 6.0.7 on 2026-07-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutpagesettings_contactpagesettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagesettings',
            name='about_text',
        ),
    ]
