# Generated by Django 6.0.7 on 2026-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_aboutpagesettings_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_col1_title',
            field=models.CharField(default='Quick Links', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_col2_title',
            field=models.CharField(default='Information', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_col3_title',
            field=models.CharField(default='Stay Updated', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_text',
            field=models.TextField(default='Subscribe to our newsletter for the latest trade updates and offers.'),
        ),
    ]
