# Generated by Django 6.0.7 on 2026-07-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_footer_col1_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_col1_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_col2_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_col3_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_newsletter_text',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com'),
        ),
    ]
