# Generated by Django 6.0.7 on 2026-07-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sitesettings_footer_col1_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram_url',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='why_choose_us_headline',
            field=models.CharField(default='Why Trade California?', max_length=255),
        ),
    ]
