# Generated by Django 6.0.7 on 2026-07-27 06:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_whychooseusitem_remove_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='overview_badge_text',
            field=models.CharField(blank=True, default='Overview', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='overview_content',
            field=tinymce.models.HTMLField(blank=True, default='<p>Founded by <strong>Andrew Hughan</strong>, former USAIF professional, <span class="font-medium">Trade California</span> is a Sacramento, California-based international trade and business development platform operated by <strong>American Green Technology, LLC.</strong></p><p>Trade California connects global buyers, distributors, governments, and business partners with trusted U.S.-based products, commodities, services, and business opportunities—helping build meaningful connections between American businesses and international markets.</p>'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='overview_tagline',
            field=models.CharField(blank=True, default='From California to the World.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='overview_title',
            field=models.CharField(blank=True, default='Connecting American Opportunity with Global Markets.', max_length=255),
        ),
    ]
