# Generated by Django 6.0.7 on 2026-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_homepagesettings_overview_badge_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='hero_headline',
            field=models.CharField(blank=True, default='About Us', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='hero_subtext',
            field=models.TextField(blank=True, default='Trade California International', null=True),
        ),
        migrations.AlterField(
            model_name='contactpagesettings',
            name='hero_headline',
            field=models.CharField(blank=True, default='Contact Us', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactpagesettings',
            name='hero_subtext',
            field=models.TextField(blank=True, default='Get in touch with our expert team today.', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_headline',
            field=models.CharField(blank=True, default='Expand Your Global Reach', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_subtext',
            field=models.TextField(blank=True, default='Premium Trade & International Business Platform', null=True),
        ),
        migrations.AlterField(
            model_name='productspagesettings',
            name='hero_headline',
            field=models.CharField(blank=True, default='Our Products', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productspagesettings',
            name='hero_subtext',
            field=models.TextField(blank=True, default='Explore our premium catalog of American products.', null=True),
        ),
        migrations.AlterField(
            model_name='registrationpagesettings',
            name='hero_headline',
            field=models.CharField(blank=True, default='Partner Registration', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrationpagesettings',
            name='hero_subtext',
            field=models.TextField(blank=True, default='Join our global network of verified trade partners.', null=True),
        ),
        migrations.AlterField(
            model_name='servicespagesettings',
            name='hero_headline',
            field=models.CharField(blank=True, default='Our Services', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicespagesettings',
            name='hero_subtext',
            field=models.TextField(blank=True, default='Comprehensive solutions for international trade.', null=True),
        ),
    ]
