# Generated by Django 6.0.7 on 2026-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_aboutpagesettings_hero_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='overview_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/overview/'),
        ),
    ]
